# Site settings
title: Blog - Dimas Maryanto
email: software.dimmaryanto@hotmail.com
fb_appid: 1172380132803751
twitter_username: dimMaryanto93

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://software.dimmaryanto93.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 3
gist:
  noscript: false

# Permalinks
permalink: berita/:categories/:title/
paginate_path: halaman-:num/

# Plugins
gems:
- jekyll-paginate
- jekyll-youtube
- jekyll-gist
- kramdown
- rouge

# jangan pake default system
exclude: [vendor]
